### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by bixiaopeng0** [yuxie11/R2D2#2]
您好，有两个问题请教一下。
<img width="394" alt="image" src="https://user-images.githubusercontent.com/31760851/172987708-1732c271-38b7-45e7-af22-57f0908c64da.png">

1、Pre-training datasets 只有23M数据集，250M数据集考虑开源吗？
2、Pre-training datasets （23M）里下载部分数据之后，发现只有文本信息，后面考虑释放图片部分数据吗？

**Comment by yuxie11** [comment]
1. We will not release 250M dataset.
2. We release the imageURL in JSON.
